# -*- coding: utf-8 -*-
"""elastic search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10K6DpTIKI1bmnDDZWwcz0tRhcOOzaHWH
"""

!python -m pip install elasticsearch

from elasticsearch import Elasticsearch

e1={
    "first_name":"saya",
    "last_name":"kandarkar",
    "age": 25,
    "about": "Love to play football",
    "interests": ['sports','music'],
}
e2={
    "first_name":"taylor",
    "last_name":"swift",
    "age": 33,
    "about": "Love to play cricket",
    "interests": ['sports','music'],
}
e3={
    "first_name":"ariana",
    "last_name":"grande",
    "age": 30,
    "about": "Love to play hockey",
    "interests": ['sports','music'],
}
print(e1,e2,e3)

es = Elasticsearch([{'host': 'localhost', 'port': 9200}])

e1={
    "first_name":"s",
    "last_name":"k",
    "age": 27,
    "about": "Love to play cricket",
    "interests": ['sports','music'],
}

res = es.index(index="employee", id=1, body=e1)
res = es.index(index="employee", id=2, body=e2)
res = es.index(index="employee", id=3, body=e3)

res = es.get(index="employee", id=3)

res= es.search(index='employee',body={'query':{'match':{'first_name':'taylor'}}})

res= es.search(index='employee',body={
        'query':{
            'bool':{
                'must':{
                    'match':{
                        'first_name':'saya'
                    }
                },
                "filter":{
                    "range":{
                        "age":{
                            "lt":26
                        }
                    }
                }
            }
        }
    })

res= es.search(index='employee',body={
        'query':{
            'match':{
                "about":"play cricket"
            }
        }
    })

res

res= es.search(index='employee',body={
        "aggs": {
            "all_interests": {
              "terms": {
                "field": "e1.interests"
              }
        }
    }
})

res